<div>
    <div transition:fly="{{ y: 180, duration: 1500 }}" class="mx-auto container">
        <div class="px-16 py-4">
            <p> Hello!<br>
                Thanks for visiting. So, how do you use this website?<br>
                Well, you just change the colors until it looks pretty (read "How does it work?" for an explanation on the colors). But how do you turn it into a something you can use?<br>
                <br>
                This website generates a .json file you can copy and paste into your folder. I tried to make it downlodable but I felt it wouldn't make this website more useful.<br>
                Anyway, let's get started.<br>
                <br>
                First, open Visual Studio Code. Now, you need to install a npm package (you need node.js btw):
            </p>
        </div>
        <div style="background-color:{bgSidebar}" class="rounded-2xl px-16 py-4">
            <pre>npm install -g yo</pre>
        </div>
        <div class="px-16 py-4 pt-6">
            <p> Next, install the Yo Generator:</p>
        </div>
        <div style="background-color:{bgSidebar}" class="rounded-2xl px-16 py-4">
            <pre>npm install -g generator-code</pre>
        </div>
        <div class="px-16 py-4 pt-6">
            <p>Then, run it:</p>
        </div>
        <div style="background-color:{bgSidebar}" class="rounded-2xl px-16 py-4">
            <pre>yo code</pre>
        </div>
        <div class="px-16 py-4 pt-6">
            <p>and select:</p>
        </div>
        <div style="background-color:{bgSidebar}" class="rounded-2xl px-16 py-4">
            <pre>> New Color Theme</pre>
        </div>
        <div class="px-16 py-4 pt-6">
            <p>Select:</p>
        </div>
        <div style="background-color:{bgSidebar}" class="rounded-2xl px-16 py-4">
            <pre>> No, start fresh </pre>
        </div>
        <div class="px-16 py-4 pt-6">
            <p>Name it, and follow the instructions (name, identifier, description, name shown to the user). You can select any of them (but pick the one closest to yours):</p>
        </div>
        <div style="background-color:{bgSidebar}" class="rounded-2xl px-16 py-4">
            <pre>
Dark
Light
High Contrast
            </pre>
        </div>
        <div class="px-16 py-4 pt-6">
            <p>You can initialize a Git repo if you want. Ok, we finished setting up. (congrats!)<br>
                There should be a .json file ([name]-theme.json) and you can just paste the generated .json file. Btw, you can test your theme by pressing "f5" or selecting "Run and Debug."<br>
                <br>
                After making your theme, setup your package.json. You can leave it alone, but you can add publisher name and such (most are for the Marketplace). Before we continue though, open the .json file (generated by this website) and make sure to edit the name and type. By default, it is "pilcrow" and "dark" respectively.<br>
                Now, we have to package it. We have to install another npm package:
            </p>
        </div>
        <div style="background-color:{bgSidebar}" class="rounded-2xl px-16 py-4">
            <pre>> npm i -g vsce </pre>
        </div>
        <div class="px-16 py-4 pt-6">
            <p>And run it:</p>
        </div> 
        <div style="background-color:{bgSidebar}" class="rounded-2xl px-16 py-4">
            <pre>vsce package </pre>
        </div>
        <div class="px-16 py-4 pt-6">
            <p>That should create a .vsix file. That's your extension, and you can download and share it too. To download it: </p>
        </div> 
        <div style="background-color:{bgSidebar}" class="rounded-2xl px-16 py-4">
            <pre>code --install-extension [package name] </pre>
        </div>
        <div class="px-16 py-4 pt-6">
            <p>That's it!</p>
        </div> 
    </div>
</div>

<script>
    import {fly} from "svelte/transition"
    import JSCode from "../components/code/JSCode.svelte";
    import HTMLCode from "../components/code/HTMLCode.svelte";
    import CSSCode from "../components/code/CSSCode.svelte";
    import VSCode from "../components/code/VSCode.svelte"
    import Menu from "../components/Menu.svelte"
    import LoadCode from "../components/code/LoadCode.svelte"
    import {codeType, colorMap} from "../javascript/stores"

    let bgSidebar;
    let textSidebar;

    $: bgSidebar = $colorMap.get("sidebar bg")
    $: textSidebar = $colorMap.get("sidebar text")
    $: console.log($codeType)

    let selectedCode;

    $: setTimeout(function(){ 
        selectedCode = $codeType;
    }, 700);

    

</script>

